apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: deeproutepipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deeproutepipelinesjavascriptdocker 
    spec:
      containers:
        - name: deeproutepipelinesjavascriptdocker 
          image: acraksdevops.azurecr.io/deeproutepipelinesjavascriptdocker
          ports:
          - containerPort: 8080