apiVersion : apps/v1
kind: Deployment
metadata:
  name: deeproutepipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeproutepipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: deeproutepipelinesjavascriptdocker 
    spec:
      containers:
        - name: deeproutepipelinesjavascriptdocker 
          image: acraksdevops.azurecr.io/deeproutepipelinesjavascriptdocker
          ports:
          - containerPort: 8080
